# Generated by Django 5.2.6 on 2025-09-14 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('interview', 'Interview'), ('offer', 'Offer'), ('rejected', 'Rejected'), ('oa', 'OA'), ('ghosted', 'No Response')], default='applied', max_length=20),
        ),
    ]
