# Generated by Django 5.2.6 on 2025-09-14 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_remove_jobapplication_notes_applicationnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
