# Generated by Django 5.2.6 on 2025-09-13 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTE', 'Note'), ('EMAIL_IN', 'Email (from company)'), ('EMAIL_OUT', 'Email (to company)'), ('CALL', 'Phone call'), ('MEETING', 'Meeting'), ('INTERVIEW', 'Interview invite'), ('OFFER', 'Offer'), ('REJECT', 'Reject')], default='NOTE', max_length=20)),
                ('content', models.TextField(blank=True)),
                ('occurred_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='notes.application')),
            ],
            options={
                'ordering': ['-occurred_at'],
            },
        ),
    ]
